#!/bin/bash
# command-chain entry for the postgresql daemon.
#
# Snap components (e.g. `snap install postgresql+pg-cron`) are mounted read-only
# under $SNAP/../components/$SNAP_REVISION/<name>/ and ship:
#   lib/*.so           -> appended to dynamic_library_path
#   share/extension/*  -> parent dir appended to extension_control_path (PG >= 18)
#   manifest           -> optional `PRELOAD=<lib>` appended to shared_preload_libraries
#   postgresql.conf    -> optional GUCs copied verbatim (extension settings)
# On every daemon start this regenerates <include_dir>/00-snap-components.conf
# in the cluster config so that adding/removing a component and restarting
# PostgreSQL is all that is needed. Failures here never block the daemon.
#
# The cluster config is owned by _daemon_ and root inside the snap has no
# CAP_DAC_OVERRIDE, so the file work is re-executed as _daemon_ via setpriv.
set -u

if [ "${1:-}" != "--as-daemon" ]; then
  if [ "$(id -u)" = "0" ]; then
    if ! "$SNAP/usr/bin/setpriv" --clear-groups --reuid _daemon_ --regid root -- "$0" --as-daemon; then
      echo "WARNING: components-env.sh: could not configure snap components, starting without them" >&2
    fi
  fi
  exec "$@"
fi

# ---- everything below runs as _daemon_ --------------------------------------
set -e
umask 022

PG_MAJOR="${SNAP_VERSION%%.*}"
CONF_DIR="$SNAP_COMMON/etc/postgresql/$PG_MAJOR/main"
PG_CONF="$CONF_DIR/postgresql.conf"
COMP_ROOT="$(dirname "$SNAP")/components/$SNAP_REVISION"

if [ ! -f "$PG_CONF" ]; then
  echo "components-env.sh: $PG_CONF not found, skipping" >&2
  exit 0
fi

# Last active value of a GUC in postgresql.conf (empty if unset/commented).
conf_get() {
  sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*'\([^']*\)'.*/\1/p" "$PG_CONF" | tail -1
}

# Debian's pg_createcluster sets include_dir = 'conf.d' (createcluster.conf).
# Clusters created by older snap revisions lack it: add it once.
include_dir="$(conf_get include_dir)"
if [ -z "$include_dir" ]; then
  include_dir=conf.d
  printf "\n# Added by the postgresql snap: settings for installed snap components.\ninclude_dir = 'conf.d'\n" >> "$PG_CONF"
fi
case "$include_dir" in
  /*) conf_d="$include_dir" ;;
  *)  conf_d="$CONF_DIR/$include_dir" ;;
esac
out="$conf_d/00-snap-components.conf"

libpath="$(conf_get dynamic_library_path)";    libpath="${libpath:-\$libdir}"
ctlpath="$(conf_get extension_control_path)";  ctlpath="${ctlpath:-\$system}"
preload="$(conf_get shared_preload_libraries)"
extra=""

for comp in "$COMP_ROOT"/*/; do
  [ -d "$comp" ] || continue
  comp="${comp%/}"
  [ -d "$comp/lib" ]             && libpath="$libpath:$comp/lib"
  [ -d "$comp/share/extension" ] && ctlpath="$ctlpath:$comp/share"  # PG appends /extension
  if [ -f "$comp/manifest" ]; then
    lib="$(sed -n 's/^PRELOAD=//p' "$comp/manifest" | tail -1)"
    case ",$preload," in
      *",$lib,"*) ;;  # already listed by the administrator
      *) [ -n "$lib" ] && preload="${preload:+$preload,}$lib" ;;
    esac
  fi
  if [ -f "$comp/postgresql.conf" ]; then
    extra="$extra
# --- $(basename "$comp") ---
$(cat "$comp/postgresql.conf")"
  fi
done

mkdir -p "$conf_d"
{
  echo "# Generated by the postgresql snap at $(date -u +%FT%TZ) from the installed"
  echo "# snap components; regenerated on every daemon start. Do not edit."
  echo "dynamic_library_path = '$libpath'"
  echo "extension_control_path = '$ctlpath'"
  [ -n "$preload" ] && echo "shared_preload_libraries = '$preload'"
  [ -n "$extra" ] && echo "$extra"
  true
} > "$out.tmp"
mv -f "$out.tmp" "$out"
