name: postgresql
base: core24
version: '16.10'
summary: PostgreSQL in a snap.
description: |
  PostgreSQL is a free and open-source relational database management
  system emphasizing extensibility and SQL compliance.

platforms:
  amd64:
  arm64:
grade: stable
confinement: strict

system-usernames:
  _daemon_: shared

plugs:
  shared-memory:
    private: true

hooks:
  install:
    plugs:
      - network

layout:
  /usr/bin/perl:
    symlink: $SNAP/usr/bin/perl
  /usr/bin/install:
    bind-file: $SNAP/usr/bin/install
  /usr/bin/pg_lsclusters:
    symlink: $SNAP/usr/bin/pg_lsclusters
  /usr/bin/pg_ctlcluster:
    symlink: $SNAP/usr/bin/pg_ctlcluster
  /usr/bin/pg_dropcluster:
    symlink: $SNAP/usr/bin/pg_dropcluster
  /usr/lib/python3/dist-packages:
    bind: $SNAP/usr/lib/python3/dist-packages
  /etc/perl:
    bind: $SNAP/etc/perl
  /usr/local/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl:
    bind: $SNAP/usr/local/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl
  /usr/local/share/perl:
    bind: $SNAP/usr/local/share/perl
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl5:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl5
  /usr/share/perl5:
    bind: $SNAP/usr/share/perl5
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base
  /usr/share/perl:
    bind: $SNAP/usr/share/perl
  /usr/local/lib/site_perl:
    bind: $SNAP/usr/local/lib/site_perl
  /usr/lib/postgresql/16:
    bind: $SNAP/usr/lib/postgresql/16
  /var/cache/postgresql:
    bind: $SNAP_COMMON/var/cache/postgresql
  /etc/postgresql:
    bind: $SNAP_COMMON/etc/postgresql
  /etc/postgresql-common:
    bind: $SNAP_COMMON/etc/postgresql-common
  /var/lib/postgresql:
    bind: $SNAP_COMMON/var/lib/postgresql
  /var/log/postgresql:
    bind: $SNAP_COMMON/var/log/postgresql
  /usr/share/postgresql:
    bind: $SNAP/usr/share/postgresql

apps:
  createdb:
    command: usr/bin/createdb
  createuser:
    command: usr/bin/createuser
  archivecleanup:
    command: archivecleanup.sh
  createcluster:
    command: create-cluster.sh
    plugs:
      - network
  dropcluster:
    command: drop-cluster.sh
  isready:
    command: usr/bin/pg_isready
  restore:
    command: usr/bin/pg_restore
    plugs:
      - network
  config:
    command: usr/bin/pg_config
  dump:
    command: usr/bin/pg_dump
    plugs:
      - network
  lsclusters:
    command: usr/bin/pg_lsclusters
  recvlogical:
    command: usr/bin/pg_recvlogical
  basebackup:
    command: usr/bin/pg_basebackup
  conftool:
    command: conftool.sh
  ctl:
    command: ctl.sh
    plugs:
      - network
      - network-bind
  ctlcluster:
    command: ctl-cluster.sh
    plugs:
      - network
      - network-bind
  dumpall:
    command: usr/bin/pg_dumpall
    plugs:
      - network
  receivewal:
    command: usr/bin/pg_receivewal
  renamecluster:
    command: rename-cluster.sh
    plugs:
      - network
      - network-bind
  pgbench:
    command: usr/bin/pgbench
  psql:
    command: usr/bin/psql
    plugs:
      - network
  postgresql:
    command: >-
      ctl-cluster.sh --skip-systemctl-redirect --foreground 16 main start
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  postgres-debs:
    plugin: nil
    stage-packages:
      - postgresql=16+257build1.1
      - util-linux
      - locales-all
      - coreutils
    override-stage: |
      craftctl default
      # Use tmp for socket
      ls -1 $SNAPCRAFT_STAGE/usr/bin/pg_* | xargs sed -i \
        's/\/var\/run\/postgresql/\/tmp/g'
      sed -i 's/\/var\/run\/postgresql/\/tmp/g' \
        $SNAPCRAFT_STAGE/usr/share/perl5/PgCommon.pm
      # Pass user in startup checks
      sed -i "s/psql -h /psql -U postgres -h /g" \
        $SNAPCRAFT_STAGE/usr/bin/pg_ctlcluster
      # Skip systemd when renaming and dropping
      sed -i \
        "s/'pg_ctlcluster',/'pg_ctlcluster', '--skip-systemctl-redirect',/g" \
        $SNAPCRAFT_STAGE/usr/bin/pg_dropcluster
      sed -i \
        "s/'pg_ctlcluster',/'pg_ctlcluster', '--skip-systemctl-redirect',/g" \
        $SNAPCRAFT_STAGE/usr/bin/pg_renamecluster
    organize:
      etc/postgresql: default-config/etc/postgresql
      etc/postgresql-common: default-config/etc/postgresql-common
      var/lib/postgresql: default-config/var/lib/postgresql
      var/log/postgresql: default-config/var/log/postgresql
      usr/share/doc/postgresql/copyright: licenses/COPYRIGHT-postgresql
      usr/share/doc/util-linux/copyright: licenses/COPYRIGHT-util-linux
      usr/share/doc/locales-all/copyright: licenses/COPYRIGHT-locales-all
  snap-license:
    plugin: dump
    source: .
    source-type: local
    stage:
      - licenses/LICENSE-snap
    organize:
      LICENSE: licenses/LICENSE-snap
  wrapper:
    plugin: dump
    source: snap/local
