name: postgresql
base: core26
build-base: devel # TODO: remove before stable release
version: '19devel'
summary: PostgreSQL in a snap.
description: |
  PostgreSQL is a free and open-source relational database management
  system emphasizing extensibility and SQL compliance.

platforms:
  amd64:
  arm64:
grade: devel # TODO: switch to stable before stable release
confinement: strict

system-usernames:
  _daemon_: shared

plugs:
  shared-memory:
    private: true

# This slot exposes all of this snap to any other snap to use postgresql without
# bundling any of postgresql. This allows multiple snaps to use the postgresql
# snap however they see fit, without duplicating postgresql files on the device
# (by bundling postgresql with every snap)
slots:
  postgresql:
    interface: content
    content: bins
    read:
      - $SNAP

hooks:
  install:
    plugs:
      - network

layout:
  /usr/bin/perl:
    symlink: $SNAP/usr/bin/perl
  /usr/lib/python3/dist-packages:
    bind: $SNAP/usr/lib/python3/dist-packages
  /etc/perl:
    bind: $SNAP/etc/perl
  /usr/local/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl:
    bind: $SNAP/usr/local/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl
  /usr/local/share/perl:
    bind: $SNAP/usr/local/share/perl
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl5:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl5
  /usr/share/perl5:
    bind: $SNAP/usr/share/perl5
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base
  /usr/share/perl:
    bind: $SNAP/usr/share/perl
  /usr/local/lib/site_perl:
    bind: $SNAP/usr/local/lib/site_perl
  /usr/lib/postgresql/19:
    bind: $SNAP/usr/lib/postgresql/19
  /var/cache/postgresql:
    bind: $SNAP_COMMON/var/cache/postgresql
  /etc/postgresql:
    bind: $SNAP_COMMON/etc/postgresql
  /var/lib/postgresql:
    bind: $SNAP_COMMON/var/lib/postgresql
  /var/log/postgresql:
    bind: $SNAP_COMMON/var/log/postgresql
  /usr/share/postgresql:
    bind: $SNAP/usr/share/postgresql

apps:
  createdb:
    command: usr/lib/postgresql/19/bin/createdb
  createuser:
    command: usr/lib/postgresql/19/bin/createuser
  archivecleanup:
    command: archivecleanup.sh
  isready:
    command: usr/lib/postgresql/19/bin/pg_isready
  restore:
    command: usr/lib/postgresql/19/bin/pg_restore
    plugs:
      - network
  config:
    command: usr/lib/postgresql/19/bin/pg_config
  dump:
    command: usr/lib/postgresql/19/bin/pg_dump
    plugs:
      - network
  recvlogical:
    command: usr/lib/postgresql/19/bin/pg_recvlogical
  basebackup:
    command: usr/lib/postgresql/19/bin/pg_basebackup
  ctl:
    command: ctl.sh
    plugs:
      - network
      - network-bind
  dumpall:
    command: usr/lib/postgresql/19/bin/pg_dumpall
    plugs:
      - network
  receivewal:
    command: usr/lib/postgresql/19/bin/pg_receivewal
  pgbench:
    command: usr/lib/postgresql/19/bin/pgbench
  psql:
    command: usr/lib/postgresql/19/bin/psql
    plugs:
      - network
  postgresql:
    command: postgres.sh
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  postgresql:
    plugin: dump
    source: bld:postgresql
    source-channel: 19-26.04/edge
    stage-packages:
      - libicu78
      - libldap2
      - libxml2-16
      - libnuma1
      - liburing2
      - perl
      - util-linux
      - locales-all
    organize:
      etc/postgresql: default-config/etc/postgresql
      var/lib/postgresql: default-config/var/lib/postgresql
      var/log/postgresql: default-config/var/log/postgresql
      usr/share/doc/postgresql/copyright: licenses/COPYRIGHT-postgresql
      usr/share/doc/util-linux/copyright: licenses/COPYRIGHT-util-linux
      usr/share/doc/locales-all/copyright: licenses/COPYRIGHT-locales-all
  snap-license:
    plugin: dump
    source: .
    source-type: local
    stage:
      - licenses/LICENSE-snap
    organize:
      LICENSE: licenses/LICENSE-snap
  wrapper:
    plugin: dump
    source: snap/local
