# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: SNAP Build/Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  lint-workflows:
    name: Lint .github/workflows/
    uses: canonical/data-platform-workflows/.github/workflows/lint_workflows.yaml@v49.0.4
    permissions:
      contents: read

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: tox run -e lint
        run: tox run -e lint
    permissions: {}

  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v49.0.4
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      contents: read

  test:
    name: Test snap | ${{ matrix.base.version }} ${{ matrix.platform.arch }}
    timeout-minutes: 10
    # runs-on: [self-hosted, linux, "${{ matrix.platform.host_arch }}", "${{ matrix.base.codename }}", large]
    runs-on: "ubuntu-${{ matrix.base.version }}${{ matrix.platform.gh_suffix }}"
    strategy:
      fail-fast: false
      matrix:
        base:
          - { codename: jammy, version: 22.04 }
          - { codename: noble, version: 24.04 }
        # - { codename: resolute, version: 26.04 }
        platform:
          - { os: linux, arch: amd64, host_arch: x64, gh_suffix: "" }
          - { os: linux, arch: arm64, host_arch: arm64, gh_suffix: "-arm" }
    needs:
      - lint-workflows
      - lint
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Download snap package(s)
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*-${{ matrix.platform.arch }}
          merge-multiple: true
      - name: Add pipx to PATH
        run: |
          echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"
          echo "/root/.local/bin" >> "${GITHUB_PATH}"
      - name: Run tests
        run: |
          # lxd is necessary for spread
          sudo snap install lxd
          # On ubuntu-22.04 runner, lxd 5.0 is installed. lxd 5.21 is needed for core26 for https://github.com/canonical/lxd/pull/17409
          sudo snap refresh lxd --channel 5.21/stable
          sudo adduser "$USER" lxd
          # `newgrp` does not work in GitHub Actions; use `sudo --user` instead
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd waitready
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd init --auto
          # Workaround for Docker & LXD on same machine
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
          sudo snap install snapcraft --classic
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- snapcraft test
    permissions: {}
