# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Snap Store

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 18-26.04
      - 19-26.04
  workflow_dispatch:

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@sd-env-production
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      contents: read

  release:
    name: Release snap
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_snap_edge_sd.yaml@sd-env-production
    with:
      track: '19-26.04'
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAP_STORE_TOKEN_EDGE }}
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      contents: write  # Needed to create git tags
