#!/bin/bash

mkdir -p "$SNAP_DATA"/etc
cp -r "$SNAP"/default-config/etc/postgresql "$SNAP_DATA"/etc
cp -r "$SNAP"/default-config/etc/postgresql-common "$SNAP_DATA"/etc

mkdir -p "$SNAP_COMMON"/pgsql/data

mkdir -p "$SNAP_COMMON"/var/lib/postgresql
mkdir -p "$SNAP_COMMON"/var/log/postgresql

chown -R 584788:root "$SNAP_COMMON"/*
chown -R 584788:root "$SNAP_DATA"/*

export LOCPATH="${SNAP}"/usr/lib/locale
export PGDATA="$SNAP_COMMON"/pgsql/data
PGMAJORVER=$(echo "$SNAP_VERSION" | cut -d "." -f 1)

"${SNAP}/usr/bin/setpriv" --clear-groups --reuid snap_daemon --regid snap_daemon -- "${SNAP}/usr/lib/postgresql/${PGMAJORVER}/bin/initdb" -U postgres -D "${PGDATA}" --auth-host scram-sha-256 --no-instructions
